version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    # Mount your application code somewhere.
    volumes:
    - .:/src/example
    # Security options required to enable delve debugger in docker
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - "SYS_PTRACE"
    # Tell the container where to find the entry point
    # to your source code.
    environment:
      SRC_ENTRYPOINT: /src/example/main.go
    ports:
    # Open delve debug port for debugging
    - 40000:40000
    # App's port
    - 8080:8080
